(() => {
'use strict';
const $=s=>document.querySelector(s), VERSION='0.8.0', CFG='davomat-terminal-config-v1', Q='davomat-offline-queue-v1';
const MODEL='https://cdn.jsdelivr.net/npm/@vladmandic/human@3.3.6/models/';
const S={cfg:null,human:null,stream:null,profiles:[],employees:new Map(),thr:{match:.62,live:.55,real:.55},samples:7,pending:null,mode:null,busy:false,running:false,hit:null,hits:0,timer:null,autoEnrollCode:null,launchEnrollCode:null,launchBackend:null};
const msg={DEVICE_AUTH_FAILED:'Қурилма рухсати рад этилди',EMPLOYEE_NOT_FOUND:'Ходим топилмади',FACE_PROOF_LOW:'Юз текширувидан ўтмади',EVENT_TYPE_MISMATCH:'Нотўғри тугма танланди',ALREADY_MARKED:'Белги жуда тез такрорланди',NETWORK_ERROR:'Интернет билан алоқа йўқ',TIMEOUT:'Сервер жавоб бермади'};
const friendly=e=>msg[String(e?.message||e||'')]||String(e?.message||e||'Номаълум хато');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const uuid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);
const ttime=d=>new Intl.DateTimeFormat('uz-UZ',{timeZone:'Asia/Tashkent',hour:'2-digit',minute:'2-digit'}).format(d||new Date());
const tdate=d=>new Intl.DateTimeFormat('uz-UZ',{timeZone:'Asia/Tashkent',day:'2-digit',month:'long',year:'numeric'}).format(d||new Date());
function show(id){['setupView','idleView','cameraView','resultView'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));}
function toast(x){const e=$('#toast');e.textContent=x;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),2500)}
function instruction(a,b=''){ $('#instruction').textContent=a; $('#subInstruction').textContent=b; }
function net(){const b=$('#netBadge'),on=navigator.onLine;b.textContent=on?'ОНЛАЙН':'ОФЛАЙН';b.className='badge '+(on?'online':'offline');}
function valid(c){return c&&/^https:\/\/script\.google\.com\/macros\/s\/.+\/exec/.test(c.url||'')&&c.deviceId&&c.deviceToken}
function saveCfg(c){localStorage.setItem(CFG,JSON.stringify(c));S.cfg=c}
function loadCfg(){try{return JSON.parse(localStorage.getItem(CFG)||'null')}catch{return null}}
function launchParams(){const p=new URLSearchParams(location.search);return {backend:(p.get('backend')||'').trim(),pair:(p.get('pair')||'').trim(),enroll:(p.get('enroll')||'').trim()}}
function jsonpTo(url,params,timeout=20000){return new Promise((res,rej)=>{const cb='__davpub_'+Date.now()+'_'+Math.floor(Math.random()*1e5),s=document.createElement('script');let done=false;const clean=()=>{delete window[cb];s.remove();clearTimeout(to)};window[cb]=d=>{if(done)return;done=true;clean();res(d)};const q=new URLSearchParams({...params,callback:cb});s.src=url+(url.includes('?')?'&':'?')+q;s.onerror=()=>{if(done)return;done=true;clean();rej(new Error('NETWORK_ERROR'))};document.head.appendChild(s);const to=setTimeout(()=>{if(done)return;done=true;clean();rej(new Error('TIMEOUT'))},timeout)})}
async function provisionLaunch(lp){if(!lp||!lp.pair||!lp.backend)return false;if(!/^https:\/\/script\.google\.com\/macros\/s\/.+\/exec/.test(lp.backend))throw new Error('PAIRING_LINK_INVALID');const r=await jsonpTo(lp.backend,{api:'provision',pair_code:lp.pair},20000);if(!r?.ok)throw new Error(r?.error||'PAIRING_FAILED');const c={url:r.backendUrl||lp.backend,deviceId:r.deviceId,deviceToken:r.deviceToken};if(!valid(c))throw new Error('PAIRING_DATA_INVALID');saveCfg(c);S.launchEnrollCode=lp.enroll||null;S.launchBackend=c.url;history.replaceState(null,'',location.pathname);return true}
function importHash(){try{const raw=new URLSearchParams(location.hash.slice(1)).get('cfg');if(!raw)return;let x=raw.replace(/-/g,'+').replace(/_/g,'/');x+='='.repeat((4-x.length%4)%4);const c=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(x),ch=>ch.charCodeAt(0))));if(valid(c)){saveCfg(c);history.replaceState(null,'',location.pathname)}}catch(e){console.warn(e)}}
function jsonp(params,timeout=20000){return new Promise((res,rej)=>{const cb='__dav_'+Date.now()+'_'+Math.floor(Math.random()*1e5),s=document.createElement('script');let done=false;const clean=()=>{delete window[cb];s.remove();clearTimeout(to)};window[cb]=d=>{if(done)return;done=true;clean();res(d)};const q=new URLSearchParams({...params,device_id:S.cfg.deviceId,device_token:S.cfg.deviceToken,callback:cb});s.src=S.cfg.url+'?'+q;s.onerror=()=>{if(done)return;done=true;clean();rej(new Error('NETWORK_ERROR'))};document.head.appendChild(s);const to=setTimeout(()=>{if(done)return;done=true;clean();rej(new Error('TIMEOUT'))},timeout)})}
async function post(payload){await fetch(S.cfg.url,{method:'POST',mode:'no-cors',cache:'no-store',headers:{'Content-Type':'text/plain'},body:JSON.stringify({...payload,deviceId:S.cfg.deviceId,deviceToken:S.cfg.deviceToken})})}
async function wait(id,timeout=45000){const st=Date.now();while(Date.now()-st<timeout){const r=await jsonp({api:'requestStatus',request_id:id},10000);if(r?.found&&r.status==='DONE')return r.result;if(r?.found&&r.status==='ERROR')throw new Error(r.result?.error||r.message||'SERVER_ERROR');await sleep(700)}throw new Error('TIMEOUT')}
function qload(){try{return JSON.parse(localStorage.getItem(Q)||'[]')}catch{return[]}}
function qsave(a){localStorage.setItem(Q,JSON.stringify(a))}
async function syncQueue(){if(!navigator.onLine||!S.cfg)return;const a=qload(),left=[];for(const ev of a){try{await post(ev);const r=await wait(ev.requestId,30000);if(!r?.ok)throw new Error(r?.reason||'SYNC_REJECTED')}catch(e){left.push(ev);break}}qsave(left.concat(a.slice(a.length-(a.length-left.length)+left.length)));}
function ticks(){const w=$('#scanTicks');w.innerHTML='';for(let i=0;i<36;i++){const e=document.createElement('span');e.className='scan-tick';e.style.transform=`translate(-50%,-50%) rotate(${i*10}deg) translateY(-190px)`;w.appendChild(e)}}
function ring(f=0){const a=[...document.querySelectorAll('.scan-tick')],n=Math.round(Math.max(0,Math.min(1,f))*a.length);a.forEach((e,i)=>{e.classList.toggle('done',i<n);e.classList.toggle('active',i===n&&n<a.length)})}
async function initHuman(){if(S.human)return;S.human=new Human.Human({backend:'webgl',modelBasePath:MODEL,cacheSensitivity:.7,face:{enabled:true,detector:{rotation:true,maxDetected:1},mesh:{enabled:true},description:{enabled:true},iris:{enabled:true},emotion:{enabled:false},antispoof:{enabled:true},liveness:{enabled:true}},body:{enabled:false},hand:{enabled:false},object:{enabled:false}});await S.human.load();await S.human.warmup()}
async function bootstrap(){const r=await jsonp({api:'bootstrap'});if(!r.ok)throw new Error(r.error);S.profiles=r.profiles||[];S.employees=new Map((r.employees||[]).map(e=>[String(e.employeeId),e]));S.thr={match:+r.settings?.matchThreshold||.62,live:+r.settings?.livenessThreshold||.55,real:+r.settings?.realnessThreshold||.55};S.samples=Math.max(6,Math.min(8,+r.settings?.enrollSampleCount||7));}
async function pending(){if(!navigator.onLine||!S.cfg||S.running)return;try{const r=await jsonp({api:'pendingEnrollment'},10000);S.pending=r?.pending?r:null;renderPending();if(S.pending&&!S.busy&&!S.running&&S.autoEnrollCode!==S.pending.code){S.autoEnrollCode=S.pending.code;const code=S.pending.code;setTimeout(()=>{if(S.pending?.code===code&&!S.running&&!S.busy)session('ENROLL')},350)}if(!S.pending)S.autoEnrollCode=null}catch(e){console.warn('pendingEnrollment',e)}}
async function loadEnrollmentByCode(code){if(!code||!S.cfg)return false;const r=await jsonp({api:'enrollment',code:code},10000);if(!r?.ok)throw new Error(r?.error||'ENROLLMENT_NOT_FOUND');S.pending={pending:true,code:r.code,employee:r.employee};renderPending();S.autoEnrollCode=r.code;setTimeout(()=>{if(S.pending?.code===r.code&&!S.running&&!S.busy)session('ENROLL')},250);return true}
function renderPending(){const b=$('#enrollBanner');b.classList.toggle('hidden',!S.pending);if(S.pending){$('#enrollBannerName').textContent=S.pending.employee?.fullName||'Ходим';$('#startEnrollBtn').textContent='РЎЙХАТГА ОЛИШНИ БОШЛАШ'}}
async function startCamera(){await stopCamera();S.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});$('#video').srcObject=S.stream;await $('#video').play();}
async function stopCamera(){S.running=false;if(S.stream){S.stream.getTracks().forEach(t=>t.stop());S.stream=null}$('#video').srcObject=null}
function photo(){const v=$('#video'),c=document.createElement('canvas');c.width=Math.min(v.videoWidth||640,800);c.height=Math.round(c.width*(v.videoHeight||480)/(v.videoWidth||640));c.getContext('2d').drawImage(v,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.72)}
function sim(a,b){let dot=0,aa=0,bb=0;for(let i=0;i<Math.min(a.length,b.length);i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i]}return dot/(Math.sqrt(aa)*Math.sqrt(bb)||1)}
function quality(f){return {emb:f?.embedding||[],live:Number(f?.live??0),real:Number(f?.real??0),score:Number(f?.score??0),size:Number(f?.box?.[2]||0)}}
function match(emb){const best=new Map();for(const p of S.profiles){const s=sim(emb,p.embedding||[]),id=String(p.employeeId);if(!best.has(id)||s>best.get(id))best.set(id,s)}const a=[...best].sort((x,y)=>y[1]-x[1]);if(!a.length)return null;const [id,score]=a[0],second=a[1]?.[1]||0;if(score<S.thr.match||score-second<.035)return null;return {emp:S.employees.get(id),score}}
async function success(r){await stopCamera();show('resultView');$('#resultIcon').textContent='✓';$('#resultTitle').textContent='МУВАФФАҚИЯТЛИ';$('#resultName').textContent=r.fullName||'';$('#resultPosition').textContent=r.position||'';$('#resultType').textContent=r.eventType==='OUT'?'КЕТДИ':'КЕЛДИ';$('#resultTime').textContent=ttime(new Date(r.serverTime||Date.now()));$('#resultNote').textContent='Белги сақланди';setTimeout(idle,2200)}
async function fail(x){await stopCamera();show('resultView');$('#resultIcon').textContent='!';$('#resultTitle').textContent='БЕЛГИЛАНМАДИ';$('#resultName').textContent='';$('#resultPosition').textContent='';$('#resultType').textContent='';$('#resultTime').textContent='';$('#resultNote').textContent=x;setTimeout(idle,2600)}
function idle(){stopCamera();S.mode=null;S.busy=false;S.hit=null;S.hits=0;show('idleView');ring(0);renderPending()}
async function attendance(face){const q=quality(face);if(q.live<S.thr.live||q.real<S.thr.real||!q.emb.length)return instruction('Камерага қаранг','Юзни тўғри ёритинг');const m=match(q.emb);if(!m?.emp){S.hit=null;S.hits=0;return instruction('Юз аниқланмади','Камерага тўғри қаранг')}if(S.hit===m.emp.employeeId)S.hits++;else{S.hit=m.emp.employeeId;S.hits=1}ring(Math.min(1,S.hits/3));if(S.hits<3)return instruction(m.emp.fullName,'Текширилмоқда…');S.busy=true;const id=uuid(),ev={id,requestId:id,action:'attendance',eventId:id,employeeId:m.emp.employeeId,clientTime:new Date().toISOString(),requestedEventType:S.mode,clientSuggestedType:S.mode,matchScore:m.score,livenessScore:q.live,realScore:q.real,blinkOk:false,photoDataUrl:photo(),offline:!navigator.onLine};try{if(!navigator.onLine){const a=qload();a.push(ev);qsave(a);await stopCamera();return success({fullName:m.emp.fullName,position:m.emp.position,eventType:S.mode,serverTime:new Date().toISOString()})}await post(ev);const r=await wait(id);if(!r?.ok)throw new Error(r?.reason||'SERVER_REJECTED');await success(r)}catch(e){await fail(friendly(e))}}
async function enroll(face){const en=S.pending?._enroll||(S.pending._enroll={arr:[],last:null,lastAt:0});const q=quality(face);if(q.live<S.thr.live||q.real<S.thr.real||!q.emb.length||q.size<120)return instruction(S.pending.employee.fullName,'Юзни рамка ичида ушланг');if(Date.now()-en.lastAt<300)return;if(en.last&&sim(q.emb,en.last)>.9995)return instruction(S.pending.employee.fullName,'Бошингизни секин айлантиринг');en.arr.push({embedding:Array.from(q.emb,v=>Math.round(v*1e6)/1e6),quality:(q.live+q.real+q.score)/3,pose:'sample-'+(en.arr.length+1)});en.last=Array.from(q.emb);en.lastAt=Date.now();ring(en.arr.length/S.samples);$('#enrollCounter').textContent=`${en.arr.length} / ${S.samples}`;instruction(S.pending.employee.fullName,en.arr.length<S.samples?'Бошингизни секин айлантиринг':'Юз сақланмоқда…');if(en.arr.length<S.samples)return;S.busy=true;const id=uuid();try{await post({id,requestId:id,action:'enroll',enrollmentCode:S.pending.code,samples:en.arr});const r=await wait(id);if(!r?.ok)throw new Error(r?.error||'ENROLL_FAILED');S.pending=null;S.autoEnrollCode=null;await bootstrap();await stopCamera();show('resultView');$('#resultIcon').textContent='✓';$('#resultTitle').textContent='ЮЗ ТАЙЁР';$('#resultName').textContent=r.fullName||'';$('#resultPosition').textContent='';$('#resultType').textContent='';$('#resultTime').textContent='';$('#resultNote').textContent='Ходим рўйхатдан ўтди';setTimeout(idle,1800)}catch(e){await fail('Рўйхатга олиш хатоси: '+friendly(e))}}
async function loop(){if(!S.running)return;requestAnimationFrame(loop);if(S.busy||loop.last&&performance.now()-loop.last<320)return;loop.last=performance.now();try{const r=await S.human.detect($('#video'));const f=r?.face?.[0];if(!f){ring(0);return instruction(S.mode==='ENROLL'?(S.pending?.employee?.fullName||'Ходим'):(S.mode==='IN'?'КЕЛДИ':'КЕТДИ'),'Юзингизни рамка ичида ушланг')}if(S.mode==='ENROLL')await enroll(f);else await attendance(f)}catch(e){console.error(e)}}
async function session(mode){if(S.running||S.busy)return;if(mode==='ENROLL'&&!S.pending)return toast('Рўйхатга олиш вазифаси йўқ');S.mode=mode;S.hit=null;S.hits=0;show('cameraView');document.querySelector('.camera-card').classList.toggle('enroll-mode',mode==='ENROLL');$('#faceScanner').className='face-scanner '+(mode==='ENROLL'?'enrolling':'recognizing');$('#enrollCounter').classList.toggle('hidden',mode!=='ENROLL');$('#modeBadge').textContent=mode==='IN'?'КЕЛДИ':mode==='OUT'?'КЕТДИ':'ЮЗНИ РЎЙХАТГА ОЛИШ';$('#enrollCounter').textContent=`0 / ${S.samples}`;instruction(mode==='ENROLL'?S.pending.employee.fullName:(mode==='IN'?'КЕЛДИ':'КЕТДИ'),mode==='ENROLL'?'Бошингизни секин айлантиринг':'Камерага қаранг');ring(0);try{await startCamera();S.running=true;loop()}catch(e){idle();toast('Камера очилмади: '+friendly(e))}}
function service(){const q=qload().length;$('#modalContent').innerHTML=`<h2>Сервис</h2><div class="service-grid"><div class="service-stat"><span>Версия</span><b>${VERSION}</b></div><div class="service-stat"><span>Юзли ходимлар</span><b>${S.employees.size}</b></div><div class="service-stat"><span>Офлайн навбат</span><b>${q}</b></div><div class="service-stat"><span>Камера</span><b>${S.stream?'ЁҚИЛГАН':'ЎЧИҚ'}</b></div></div><button id="reload" class="secondary-btn">Базани янгилаш</button><button id="reset" class="secondary-btn">Терминал созламалари</button>`;$('#modal').classList.remove('hidden');$('#reload').onclick=()=>bootstrap().then(()=>toast('База янгиланди'));$('#reset').onclick=()=>{localStorage.removeItem(CFG);location.reload()}}
async function boot(){const lp=launchParams();try{importHash();if(lp.pair&&lp.backend)await provisionLaunch(lp);S.cfg=loadCfg();if(!valid(S.cfg)){show('setupView');$('#setupError').textContent='Терминал ҳали уланмаган. Администратор орқали бир марта уланг.';return}show('idleView');await Promise.all([initHuman(),bootstrap()]);const enrollCode=S.launchEnrollCode||lp.enroll||'';if(enrollCode)await loadEnrollmentByCode(enrollCode);else await pending();syncQueue();setInterval(pending,4000);setInterval(()=>navigator.onLine&&syncQueue(),30000)}catch(e){console.error(e);await stopCamera();show('setupView');$('#setupError').textContent='Терминал серверга уланмади. «Қайта уриниш» ни босинг.';const detail=$('#setupDetail');if(detail)detail.textContent=friendly(e)}}
function clock(){const n=new Date();$('#idleClock').textContent=ttime(n);$('#idleDate').textContent=tdate(n)}
ticks();clock();setInterval(clock,1000);net();window.addEventListener('online',()=>{net();syncQueue();pending()});window.addEventListener('offline',net);
$('#retrySetupBtn').onclick=()=>location.reload();$('#inBtn').onclick=()=>session('IN');$('#outBtn').onclick=()=>session('OUT');$('#startEnrollBtn').onclick=()=>session('ENROLL');$('#cancelCameraBtn').onclick=idle;$('#adminBtn').onclick=service;$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.add('hidden')};
boot();
})();
